FROM krot/srk-cuda-base
MAINTAINER Oleg Shyshkov <shyshkov.oleg@gmail.com>

RUN apt-get update && apt-get install -y --no-install-recommends \
	cmake \
	libboost-filesystem-dev \
	libboost-system-dev \
	libboost-random-dev \
	libboost-thread-dev \
	libboost-program-options-dev \
	libnetcdf-dev
